const products = [
    {
        id: 0,
        name: "RayBan",
        price: 1299,
        instock: 50,
        imgSrc: "img/glass2.jpeg",
    },
    {
        id: 1,
        name: "Adensco",
        price: 2399,
        instock: 50,
        imgSrc: "img/glass1.jpeg",
    },
    {
        id: 2,
        name: "Guess",
        price: 1999,
        instock: 50,
        imgSrc: "img/glass3.jpeg",
    },
    {
        id: 3,
        name: "Lacoste",
        price: 2599,
        instock: 50,
        imgSrc: "img/glass4.jpeg",
    },
    {
        id: 4,
        name: "Oakley",
        price: 2199,
        instock: 50,
        imgSrc: "img/glass5.jpeg",
    },
    {
        id: 5,
        name: "Gucci",
        price: 1799,
        instock: 50,
        imgSrc: "img/glass6.jpeg",
    },
    {
        id: 6,
        name: "Polo",
        price: 1199,
        instock: 50,
        imgSrc: "img/glass7.jpeg",
    },
    {
        id: 7,
        name: "Tom Ford",
        price: 1599,
        instock: 50,
        imgSrc: "img/glass8.jpeg",
    },
    {
        id: 8,
        name: "Dior",
        price: 5000,
        instock: 50,
        imgSrc: "img/glass9.png",
    },
    {
        id: 9,
        name: "Joe",
        price: 1299,
        instock: 50,
        imgSrc: "img/glass10.png",
    },
    {
        id: 10,
        name: "Coach",
        price: 1499,
        instock: 50,
        imgSrc: "img/glass11.png",
    },
    {
        id: 11,
        name: "Denim",
        price: 3499,
        instock: 50,
        imgSrc: "img/glass12.png",
    },
];